### ISSUE TITLE
Is this licensed

### ISSUE THREAD

**Issue by karambir** [mitul45/ta-calendar#2]
Hey, I like this project. I wanted to try it out and even forked it. But wanted to know if this is licensed as I might want to do some changes. (I will not be able to use it even if it is not licensed)

**Comment by mitul45** [comment]
Thanks for pointing it out @akarambir, I want people to use and if required work on it. Didn't know that required licence, have add it now: https://github.com/mitul45/ta-calendar/commit/70cbb3476bbeab55bddb9635b1eacc907ae17223.

Let me know how it turns out to be 🚀
